version: '3.7'
services:
  db:
    image: postgres:11.4
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_USER=${USER}
  redis:
    image: redis:latest
    ports:
      - "127.0.0.1:6379:6379"
  mailcatcher:
    image: tophfr/mailcatcher
    ports:
      - "127.0.0.1:1080:80"
      - "127.0.0.1:1025:25"
